''' <summary>
''' Welcome screen of the IDEA AddOn, code generated by Visual Studio
''' </summary>
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Public Class WndWelcome
	Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.ButtonReleaseManager = New System.Windows.Forms.Button()
        Me.ButtonExcelImporter = New System.Windows.Forms.Button()
        Me.ButtonSimpleQuery = New System.Windows.Forms.Button()
        Me.ButtonSettings = New System.Windows.Forms.Button()
        Me.TextBoxVersion = New System.Windows.Forms.TextBox()
        Me.ButtonDiagram2WPP = New System.Windows.Forms.Button()
        Me.ButtonOrphans = New System.Windows.Forms.Button()
        Me.ButtonOrphan = New System.Windows.Forms.Button()
        Me.ToolTipWelcome = New System.Windows.Forms.ToolTip(Me.components)
        Me.Button1 = New System.Windows.Forms.Button()
        Me.Button2 = New System.Windows.Forms.Button()
        Me.SuspendLayout()
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.Location = New System.Drawing.Point(16, 11)
        Me.Label1.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(443, 20)
        Me.Label1.TabIndex = 1
        Me.Label1.Text = "IDEA and TEA addon for Sparx Enterprise Architect"
        '
        'TextBox1
        '
        Me.TextBox1.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer))
        Me.TextBox1.Location = New System.Drawing.Point(16, 247)
        Me.TextBox1.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.TextBox1.Multiline = True
        Me.TextBox1.Name = "TextBox1"
        Me.TextBox1.ReadOnly = True
        Me.TextBox1.Size = New System.Drawing.Size(736, 67)
        Me.TextBox1.TabIndex = 2
        Me.TextBox1.TabStop = False
        Me.TextBox1.Text = "This AddOn is developed by Interactory under the EUPL license. " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "More information" &
    " and download: https://data-docent.nl/ideaen.aspx" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & " Developed by Bert Dingemans"
        Me.TextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center
        '
        'ButtonReleaseManager
        '
        Me.ButtonReleaseManager.Location = New System.Drawing.Point(20, 379)
        Me.ButtonReleaseManager.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.ButtonReleaseManager.Name = "ButtonReleaseManager"
        Me.ButtonReleaseManager.Size = New System.Drawing.Size(103, 63)
        Me.ButtonReleaseManager.TabIndex = 4
        Me.ButtonReleaseManager.Text = "Release manager"
        Me.ToolTipWelcome.SetToolTip(Me.ButtonReleaseManager, "Use release manager in the repository")
        Me.ButtonReleaseManager.UseVisualStyleBackColor = True
        '
        'ButtonExcelImporter
        '
        Me.ButtonExcelImporter.Location = New System.Drawing.Point(149, 379)
        Me.ButtonExcelImporter.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.ButtonExcelImporter.Name = "ButtonExcelImporter"
        Me.ButtonExcelImporter.Size = New System.Drawing.Size(92, 63)
        Me.ButtonExcelImporter.TabIndex = 5
        Me.ButtonExcelImporter.Text = "Excel importer"
        Me.ToolTipWelcome.SetToolTip(Me.ButtonExcelImporter, "Excel importer and normalizer function")
        Me.ButtonExcelImporter.UseVisualStyleBackColor = True
        '
        'ButtonSimpleQuery
        '
        Me.ButtonSimpleQuery.Location = New System.Drawing.Point(643, 379)
        Me.ButtonSimpleQuery.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.ButtonSimpleQuery.Name = "ButtonSimpleQuery"
        Me.ButtonSimpleQuery.Size = New System.Drawing.Size(111, 63)
        Me.ButtonSimpleQuery.TabIndex = 9
        Me.ButtonSimpleQuery.Text = "Simple query"
        Me.ToolTipWelcome.SetToolTip(Me.ButtonSimpleQuery, "Use the simple sql query window")
        Me.ButtonSimpleQuery.UseVisualStyleBackColor = True
        '
        'ButtonSettings
        '
        Me.ButtonSettings.Location = New System.Drawing.Point(505, 379)
        Me.ButtonSettings.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.ButtonSettings.Name = "ButtonSettings"
        Me.ButtonSettings.Size = New System.Drawing.Size(111, 63)
        Me.ButtonSettings.TabIndex = 11
        Me.ButtonSettings.Text = "Settings"
        Me.ToolTipWelcome.SetToolTip(Me.ButtonSettings, "Go to the settings window")
        Me.ButtonSettings.UseVisualStyleBackColor = True
        '
        'TextBoxVersion
        '
        Me.TextBoxVersion.BackColor = System.Drawing.Color.Lavender
        Me.TextBoxVersion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.TextBoxVersion.Enabled = False
        Me.TextBoxVersion.Location = New System.Drawing.Point(19, 331)
        Me.TextBoxVersion.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.TextBoxVersion.Name = "TextBoxVersion"
        Me.TextBoxVersion.Size = New System.Drawing.Size(734, 22)
        Me.TextBoxVersion.TabIndex = 12
        Me.TextBoxVersion.TabStop = False
        Me.TextBoxVersion.TextAlign = System.Windows.Forms.HorizontalAlignment.Center
        '
        'ButtonDiagram2WPP
        '
        Me.ButtonDiagram2WPP.Location = New System.Drawing.Point(268, 379)
        Me.ButtonDiagram2WPP.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.ButtonDiagram2WPP.Name = "ButtonDiagram2WPP"
        Me.ButtonDiagram2WPP.Size = New System.Drawing.Size(92, 63)
        Me.ButtonDiagram2WPP.TabIndex = 13
        Me.ButtonDiagram2WPP.Text = "Diagram 2 WPP"
        Me.ToolTipWelcome.SetToolTip(Me.ButtonDiagram2WPP, "Batch export for creating png files for the diagrams in the repository")
        Me.ButtonDiagram2WPP.UseVisualStyleBackColor = True
        '
        'ButtonOrphans
        '
        Me.ButtonOrphans.Location = New System.Drawing.Point(0, 0)
        Me.ButtonOrphans.Name = "ButtonOrphans"
        Me.ButtonOrphans.Size = New System.Drawing.Size(75, 23)
        Me.ButtonOrphans.TabIndex = 0
        '
        'ButtonOrphan
        '
        Me.ButtonOrphan.Location = New System.Drawing.Point(387, 379)
        Me.ButtonOrphan.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.ButtonOrphan.Name = "ButtonOrphan"
        Me.ButtonOrphan.Size = New System.Drawing.Size(92, 63)
        Me.ButtonOrphan.TabIndex = 14
        Me.ButtonOrphan.Text = "Orphans"
        Me.ToolTipWelcome.SetToolTip(Me.ButtonOrphan, "Move orphan elements to the orphans package")
        Me.ButtonOrphan.UseVisualStyleBackColor = True
        '
        'ToolTipWelcome
        '
        Me.ToolTipWelcome.IsBalloon = True
        Me.ToolTipWelcome.ToolTipTitle = "Helper info"
        '
        'Button1
        '
        Me.Button1.BackColor = System.Drawing.SystemColors.Window
        Me.Button1.BackgroundImage = Global.IDEA.My.Resources.Resources.InterActorylogoklein
        Me.Button1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center
        Me.Button1.Location = New System.Drawing.Point(16, 33)
        Me.Button1.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(443, 194)
        Me.Button1.TabIndex = 6
        Me.Button1.UseVisualStyleBackColor = False
        '
        'Button2
        '
        Me.Button2.BackColor = System.Drawing.SystemColors.Window
        Me.Button2.BackgroundImage = Global.IDEA.My.Resources.Resources.BannerHoog
        Me.Button2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center
        Me.Button2.Location = New System.Drawing.Point(456, 33)
        Me.Button2.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.Button2.Name = "Button2"
        Me.Button2.Size = New System.Drawing.Size(296, 194)
        Me.Button2.TabIndex = 15
        Me.Button2.UseVisualStyleBackColor = False
        '
        'WndWelcome
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(769, 446)
        Me.Controls.Add(Me.Button2)
        Me.Controls.Add(Me.ButtonOrphan)
        Me.Controls.Add(Me.ButtonDiagram2WPP)
        Me.Controls.Add(Me.TextBoxVersion)
        Me.Controls.Add(Me.ButtonSettings)
        Me.Controls.Add(Me.ButtonSimpleQuery)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.ButtonExcelImporter)
        Me.Controls.Add(Me.ButtonReleaseManager)
        Me.Controls.Add(Me.TextBox1)
        Me.Controls.Add(Me.Label1)
        Me.Margin = New System.Windows.Forms.Padding(3, 2, 3, 2)
        Me.Name = "WndWelcome"
        Me.Text = "Welcome to IDEA and TEA"
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents TextBox1 As System.Windows.Forms.TextBox
    Friend WithEvents ButtonReleaseManager As System.Windows.Forms.Button
    Friend WithEvents ButtonExcelImporter As System.Windows.Forms.Button
    Friend WithEvents Button1 As System.Windows.Forms.Button
    Friend WithEvents ButtonSimpleQuery As System.Windows.Forms.Button
    Friend WithEvents ButtonSettings As System.Windows.Forms.Button
    Friend WithEvents TextBoxVersion As System.Windows.Forms.TextBox
    Friend WithEvents ButtonDiagram2WPP As System.Windows.Forms.Button
    Friend WithEvents ButtonOrphans As Windows.Forms.Button
    Friend WithEvents ButtonOrphan As Windows.Forms.Button
    Friend WithEvents ToolTipWelcome As Windows.Forms.ToolTip
    Friend WithEvents Button2 As Windows.Forms.Button
End Class
