'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IDEA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationCollaboration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationCollaboration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationComponent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationComponent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationEvent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationEvent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationFunction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationFunction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationInteraction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationInteraction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationInterface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationInterface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationProcess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationProcess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ApplicationService() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ApplicationService", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Artifact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Artifact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Assessment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Assessment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessActor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessActor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessCollaboration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessCollaboration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessEvent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessEvent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessInteraction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessInteraction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessInterface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessInterface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessObject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessObject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessProcess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessProcess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessRole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessRole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_BusinessService() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_BusinessService", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Capability() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Capability", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_CommunicationNetwork() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_CommunicationNetwork", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Constraint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Constraint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Contract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Contract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_CourseOfAction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_CourseOfAction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_DataObject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_DataObject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Deliverable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Deliverable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Device() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Device", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_DistributionNetwork() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_DistributionNetwork", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Driver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Driver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Equipment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Equipment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Facility() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Facility", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Gap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Gap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Goal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Goal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Grouping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Grouping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ImplementationEvent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ImplementationEvent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Junction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Junction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Material() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Material", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Meaning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Meaning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Node() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Node", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Outcome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Outcome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Path() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Path", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Plateau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Plateau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Principle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Principle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Product() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Product", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Representation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Representation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Requirement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Requirement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Resource() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Resource", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Stakeholder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Stakeholder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_SystemSoftware() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_SystemSoftware", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_TechnologyCollaboration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_TechnologyCollaboration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_TechnologyEvent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_TechnologyEvent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_TechnologyFunction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_TechnologyFunction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_TechnologyInteraction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_TechnologyInteraction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_TechnologyInterface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_TechnologyInterface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_TechnologyProcess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_TechnologyProcess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_TechnologyService() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_TechnologyService", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_Value() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_Value", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_ValueStream() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_ValueStream", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArchiMate_WorkPackage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchiMate_WorkPackage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BannerHoog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BannerHoog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property busy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("busy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eaxpertise_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eaxpertise-small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InterActorylogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InterActorylogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InterActorylogoklein() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InterActorylogoklein", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
